channels:
- conda-forge
- bioconda
dependencies:
- bioconda::clusty=1.2.0
- bioconda::kmer-db=2.3.1
- bioconda::lz-ani=1.2.3
- bioconda::mcl=22.282
- bioconda::seqkit=2.11.0
- conda-forge::csvtk=0.36.0
- conda-forge::polars=1.35.2
- conda-forge::python=3.14.0
- conda-forge::zstd=1.5.7
